export const buyerLocation = [
  { value: 'ID', path: 'ID' },
  { value: 'Street 1', path: 'Street1' },
  { value: 'Street 2', path: 'Street2' },
  { value: 'City', path: 'City' },
  { value: 'State', path: 'State' },
  { value: 'Zip', path: 'Zip' },
  { value: 'Country', path: 'Country' },
  { value: 'Company Name', path: 'CompanyName' },
  { value: 'Primary Contact Name', path: 'xp.PrimaryContactName' },
  { value: 'Email', path: 'xp.Email' },
  { value: 'Phone', path: 'Phone' },
  { value: 'Opening Date', path: 'xp.OpeningDate' },
  { value: 'Billing Number', path: 'xp.BillingNumber' },
  { value: 'Status', path: 'xp.Status' },
  { value: 'Legal Entity', path: 'xp.LegalEntity' },
]

export const salesOrderDetail = [
  { value: 'ID', path: 'ID' },
  { value: 'Order Date', path: 'DateSubmitted' },
  { value: 'Total', path: 'Total' },
  { value: 'Tax', path: 'TaxCost' },
  { value: 'Shipping/Freight', path: 'ShippingCost' },
  { value: 'Discount', path: 'PromotionDiscount' },
  { value: 'Subtotal', path: 'Subtotal' },
  { value: 'Order Currency', path: 'xp.Currency' },
  { value: 'Submitted Order Status', path: 'xp.SubmittedOrderStatus' },
  { value: 'Shipping Status', path: 'xp.ShippingStatus' },
  { value: 'Payment Method', path: 'xp.PaymentMethod' },
  { value: 'Billing Street 1', path: 'BillingAddress.Street1' },
  { value: 'Billing Street 2', path: 'BillingAddress.Street2' },
  { value: 'Billing City', path: 'BillingAddress.City' },
  { value: 'Billing State', path: 'BillingAddress.State' },
  { value: 'Billing Zip', path: 'BillingAddress.Zip' },
  { value: 'Billing Country', path: 'BillingAddress.Country' },
  { value: 'Billing Number', path: 'BillingAddress.xp.BillingNumber' },
  { value: 'Club Number', path: 'BillingAddress.xp.LocationID' },
  { value: 'User ID', path: 'FromUser.ID' },
  { value: 'Username', path: 'FromUser.Username' },
  { value: 'First Name', path: 'FromUser.FirstName' },
  { value: 'Last Name', path: 'FromUser.LastName' },
  { value: 'Email', path: 'FromUser.Email' },
  { value: 'Phone', path: 'FromUser.Phone' },
  { value: 'Shipping First Name', path: 'xp.ShippingAddress.FirstName' },
  { value: 'Shipping Last Name', path: 'xp.ShippingAddress.LastName' },
  { value: 'Shipping Street 1', path: 'xp.ShippingAddress.Street1' },
  { value: 'Shipping Street 2', path: 'xp.ShippingAddress.Street2' },
  { value: 'Shipping City', path: 'xp.ShippingAddress.City' },
  { value: 'Shipping State', path: 'xp.ShippingAddress.State' },
  { value: 'Shipping Zip', path: 'xp.ShippingAddress.Zip' },
  { value: 'Shipping Country', path: 'xp.ShippingAddress.Country' },
]

export const purchaseOrderDetail = [
  { value: 'ID', path: 'ID' },
  { value: 'Supplier ID', path: 'ToCompanyID' },
  { value: 'Order Date', path: 'DateSubmitted' },
  { value: 'Total', path: 'Total' },
  { value: 'Order Currency', path: 'xp.Currency' },
  { value: 'Submitted Order Status', path: 'xp.SubmittedOrderStatus' },
  { value: 'Shipping Status', path: 'xp.ShippingStatus' },
  { value: 'Payment Method', path: 'xp.PaymentMethod' },
  { value: 'User ID', path: 'FromUser.ID' },
  { value: 'Username', path: 'FromUser.Username' },
  { value: 'First Name', path: 'FromUser.FirstName' },
  { value: 'Last Name', path: 'FromUser.LastName' },
  { value: 'Email', path: 'FromUser.Email' },
  { value: 'Phone', path: 'FromUser.Phone' },
  { value: 'Shipping First Name', path: 'xp.ShippingAddress.FirstName' },
  { value: 'Shipping Last Name', path: 'xp.ShippingAddress.LastName' },
  { value: 'Shipping Street 1', path: 'xp.ShippingAddress.Street1' },
  { value: 'Shipping Street 2', path: 'xp.ShippingAddress.Street2' },
  { value: 'Shipping City', path: 'xp.ShippingAddress.City' },
  { value: 'Shipping State', path: 'xp.ShippingAddress.State' },
  { value: 'Shipping Zip', path: 'xp.ShippingAddress.Zip' },
  { value: 'Shipping Country', path: 'xp.ShippingAddress.Country' },
]

export const lineItemDetail = [
  { value: 'Order ID', path: 'HSOrder.ID' },
  { value: 'Supplier ID', path: 'HSLineItem.SupplierID' },
  { value: 'Order Date', path: 'HSOrder.DateSubmitted' },
  { value: 'Total', path: 'HSOrder.Total' },
  { value: 'Tax', path: 'HSOrder.TaxCost' },
  { value: 'Shipping/Freight', path: 'HSOrder.ShippingCost' },
  { value: 'Discount', path: 'HSOrder.PromotionDiscount' },
  { value: 'Subtotal', path: 'HSOrder.Subtotal' },
  { value: 'Order Currency', path: 'HSOrder.xp.Currency' },
  {
    value: 'Submitted Order Status',
    path: 'HSOrder.xp.SubmittedOrderStatus',
  },
  { value: 'Payment Method', path: 'HSOrder.xp.PaymentMethod' },
  { value: 'Line Item ID', path: 'HSLineItem.ID' },
  { value: 'Product ID', path: 'HSLineItem.ProductID' },
  { value: 'Product Name', path: 'HSLineItem.Product.Name' },
  { value: 'Variant ID', path: 'HSLineItem.Variant.ID' },
  { value: 'Product Price', path: 'HSLineItem.UnitPrice' },
  { value: 'Quantity Ordered', path: 'HSLineItem.Quantity' },
  { value: 'Tax Code', path: 'HSLineItem.Product.xp.Tax.Code' },
  { value: 'Is Resale?', path: 'HSLineItem.Product.xp.IsResale' },
  {
    value: 'Unit of Measure Qty',
    path: 'HSLineItem.Product.xp.UnitOfMeasure.Qty',
  },
  {
    value: 'Unit of Measure',
    path: 'HSLineItem.Product.xp.UnitOfMeasure.Unit',
  },
  {
    value: 'Has Variants?',
    path: 'HSLineItem.Product.xp.HasVariants',
  },
  { value: 'Ship Method', path: 'HSLineItem.xp.ShipMethod' },
  {
    value: 'Shipping First Name',
    path: 'HSLineItem.ShippingAddress.FirstName',
  },
  {
    value: 'Shipping Last Name',
    path: 'HSLineItem.ShippingAddress.LastName',
  },
  {
    value: 'Shipping Street 1',
    path: 'HSLineItem.ShippingAddress.Street1',
  },
  {
    value: 'Shipping Street 2',
    path: 'HSLineItem.ShippingAddress.Street2',
  },
  { value: 'Shipping City', path: 'HSLineItem.ShippingAddress.City' },
  {
    value: 'Shipping State',
    path: 'HSLineItem.ShippingAddress.State',
  },
  { value: 'Shipping Zip', path: 'HSLineItem.ShippingAddress.Zip' },
  {
    value: 'Shipping Country',
    path: 'HSLineItem.ShippingAddress.Country',
  },
  {
    value: 'Billing Street 1',
    path: 'HSOrder.BillingAddress.Street1',
  },
  {
    value: 'Billing Street 2',
    path: 'HSOrder.BillingAddress.Street2',
  },
  { value: 'Billing City', path: 'HSOrder.BillingAddress.City' },
  { value: 'Billing State', path: 'HSOrder.BillingAddress.State' },
  { value: 'Billing Zip', path: 'HSOrder.BillingAddress.Zip' },
  { value: 'Billing Country', path: 'HSOrder.BillingAddress.Country' },
  {
    value: 'Billing Number',
    path: 'HSLineItem.ShippingAddress.xp.BillingNumber',
  },
  {
    value: 'Club Number',
    path: 'HSLineItem.ShippingAddress.xp.LocationID',
  },
  { value: 'User ID', path: 'HSOrder.FromUser.ID' },
  { value: 'Username', path: 'HSOrder.FromUser.Username' },
  { value: 'First Name', path: 'HSOrder.FromUser.FirstName' },
  { value: 'Last Name', path: 'HSOrder.FromUser.LastName' },
  { value: 'Email', path: 'HSLineItem.ShippingAddress.xp.Email' },
  { value: 'Phone', path: 'HSOrder.FromUser.Phone' },
]
